### ISSUE TITLE
require('jsdom'), if called within a large loop, is causing memory issues

### ISSUE THREAD

**Issue by akhoury** [NotNinja/europa#42]
basically this [line](https://github.com/neocotic/html.md/blob/master/src/md.coffee#L147)

I was trying to markdown an array of 350k records, kept running into memory allocation problems, I was able to narrow it down to the synchronous `require('jsdom')` being called every time.

**Comment by neocotic** [comment]
I know it's been a crazy long time, but I finally got around to completely rewriting this library. It's even got a new name, Europa.

As part of this big rewrite, I split this project into multiple modules. Now if you only want to use it in Node.js, you just need `node-europa`. The CLI is included in that module as well.

This issue was a key driver for how Node.js implementation and new API would work. I even included an example in the documentation for the new `Europa#release` method: https://github.com/NotNinja/europa#release

``` javascript
var europa = new Europa({ inline: true });

var input = [
  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>',
  '<p>Etiam sed felis ligula. Maecenas sit amet tristique risus...</p>',
  '<p>In dictum consequat nulla at lobortis...</p>'
];
var output = input.map(function(html) {
  return europa.convert(html);
});

europa.release();

// ...

europa.convert('Wow! <a href="https://github.com/NotNinja/europa">Europa</a> is awesome!');
//=> "Wow! [Europa](https://github.com/NotNinja/europa) is awesome!"
```

A virtual window is only created when you call `Europa#convert` and only when one hasn't already been created for that `Europa` instance. Not only does it mean that you can now have separate virtual windows on multiple instances (good for parallel flows), but you can now manually close a virtual window on any of these instances, at any time, freeing up resources. 

`jsdom` has also been upgraded to v11. So, while this means that you must have at least Node.js version 6 (in order to be compatible with `jsdom`), it means no more contextify (good bye node-gyp and Windows build issues) and lots of bug fixes and performance improvements.

I'm closing this PR now as it's no longer valid for this repo. If you still use `html-md`, please give `node-europa` a shot and let me know how you get on.

Sorry again for the massive delay.
