### ISSUE TITLE
trailing spaces in html elements cause invalid markdown

### ISSUE THREAD

**Issue by mrmoses** [NotNinja/europa#46]
`<i>some text </i> here` converts to `_some text _ here`

[Markdown syntax documentation](http://daringfireball.net/projects/markdown/syntax#em) says:

> if you surround an \* or _ with spaces, it’ll be treated as a literal asterisk or underscore

So when `_some text _ here` is converted back to HTML it results in `_some text _ here` instead of `<i>some text</i> here`

**Comment by neocotic** [comment]
Wow! It's been a very very long time... I'm so sorry. I finally got around to doing the massive rewrite of this library that I wanted to. It's been renamed Europa and it's totally changed.

Unfortunately, this issue still exists in Europa. While I completely rewrote the code from scratch, the same logic exists for each tag.

As part of the rewrite I split the the project into multiple modules to simplify everything. This means that all logic now exists within [europa-core](https://github.com/NotNinja/europa-core).

Now I don't know if you still use `html-md` or if you'd want to see this change make it into Europa, but if you do, can you please open a similar PR against `europa-core`?  I'd love to see this fix make it in. I'm trying to pay more attention to my more popular projects but each of them have required big rewrites to make them more maintainable, which was always off-putting and a little bit scary.

Also, please make sure that you open a separate PR against [europa-test](https://github.com/NotNinja/europa-test) so that these great tests are included and used to cover both versions of europa (and more, in the future).

I'm closing this PR now as it's no longer valid for this repo. If you still use `html-md`, please give `europa` a shot and let me know how you get on.

Sorry again for the massive delay.

----

P.S. You'll be happy to know that I'm split up the project into multiple modules so `europa` is now for browsers only and `node-europa` is now for Node.js (incl. CLI). Also, I've bumped the version of `jsdom` required by `node-europa` to 11. While this means that `node-europa` must require Node.js version 6 or newer now, it also means that we no longer have to deal with contextify. So no more node-gyp or Windows issues. This should hopefully make development easier for you.
